spring:
  application:
    name: gateway
  profiles:
    default: local
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: backend-route
              uri: lb://kortex
              predicates:
                - Path=/api/**
            - id: kortex-actuator
              uri: lb://kortex
              predicates:
                - Path=/kortex/actuator/**
              filters:
                - StripPrefix=1

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, refresh, env
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: gateway