spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: backend-route
              uri: lb://kortex
              predicates:
                - Path=/api/**

            - id: kortex-actuator
              uri: lb://kortex
              predicates:
                - Path=/kortex/actuator/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator + Prometheus exposure
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, refresh, env
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: gateway
