spring:
  application:
    name: eureka
  profiles:
    default: local

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: eureka