spring:
  application:
    name: kortex
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

server:
  port: ${SERVER_PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, refresh, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: kortex