spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/dima9997038/KortexVTreadsKotlin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
  instance:
    prefer-ip-address: true