spring:
  application:
    name: config-server
  profiles:
    default: local
  cloud:
    config:
      server:
        git:
          default-label: ${CONFIG_GIT_BRANCH:master}
          clone-on-start: true
          refresh-rate: ${CONFIG_GIT_REFRESH_RATE:30}

server:
  port: ${SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: config-server